name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-node:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show Node.js version
        run: node --version

      - name: Show npm version
        run: npm --version

      - name: Install dependencies
        run: npm install

      - name: Install Grunt
        run: npm install grunt
